const availableHits = [
  {
    show: ".",
    run: 0,
    isOut: false,
    isRunByBatsman: true,
    isRunByBowler: true,
    isBall: true,
  },
  {
    show: "1",
    run: 1,
    isOut: false,
    isRunByBatsman: true,
    isRunByBowler: true,
    isBall: true,
  },
  {
    show: "2",
    run: 2,
    isOut: false,
    isRunByBatsman: true,
    isRunByBowler: true,
    isBall: true,
  },
  {
    show: "3",
    run: 3,
    isOut: false,
    isRunByBatsman: true,
    isRunByBowler: true,
    isBall: true,
  },
  {
    show: "4",
    run: 4,
    isOut: false,
    isRunByBatsman: true,
    isRunByBowler: true,
    isBall: true,
  },
  {
    show: "5",
    run: 5,
    isOut: false,
    isRunByBatsman: true,
    isRunByBowler: true,
    isBall: true,
  },
  {
    show: "6",
    run: 6,
    isOut: false,
    isRunByBatsman: true,
    isRunByBowler: true,
    isBall: true,
  },
  {
    show: "wd",
    run: 1,
    isOut: false,
    isRunByBatsman: false,
    isRunByBowler: true,
    isBall: false,
  },
  {
    show: "nb",
    run: 1,
    isOut: false,
    isRunByBatsman: false,
    isRunByBowler: true,
    isBall: false,
  },
  {
    show: "1b",
    run: 1,
    isOut: false,
    isRunByBatsman: false,
    isRunByBowler: false,
    isBall: true,
  },
  {
    show: "2b",
    run: 2,
    isOut: false,
    isRunByBatsman: false,
    isRunByBowler: false,
    isBall: true,
  },
  {
    show: "4b",
    run: 4,
    isOut: false,
    isRunByBatsman: false,
    isRunByBowler: false,
    isBall: true,
  },
  {
    show: "5b",
    run: 5,
    isOut: false,
    isRunByBatsman: false,
    isRunByBowler: false,
    isBall: true,
  },
  {
    show: "w",
    run: 0,
    isOut: true,
    isRunByBatsman: false,
    isRunByBowler: false,
    isBall: true,
  },
  {
    show: "ro",
    run: 0,
    isOut: true,
    isRunByBatsman: false,
    isRunByBowler: false,
    isBall: false,
  },
];
export default availableHits;
